version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "4000:4000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "6000:6000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
