version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "4002:4002"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8005:8005"
    environment:
      - FLASK_ENV=development
    # volumes:
    #   - ./backend:/app
