version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "4001:4001"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    # volumes:
    #   - ./backend:/app
